version: '3.5'
services:
  api:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    volumes:
      - .:/go/load-test-sample
    command: realize start --run cmd/api --no-config
    ports:
      - 28080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passw0rd
    ports:
      - 23306:3306

  page:
    image: python:3.7-alpine
    volumes:
      - ./display:/var/www/html
    working_dir: /var/www/html
    command: python -m http.server 8000
    ports:
      - 28000:8000
